### ISSUE TITLE
Too many toolbar icons for some people

### ISSUE THREAD

**Issue by FlynnFarrow** [FlynnFarrow/DisableCoreGUIFunctions#2]
This is just a visual issue, however some users find it annoying with the plugin taking around 8 toolbar buttons.

This issue doesn't affect everyone, including me due to a dropdown button to see all the options on some computers.

**Comment by FlynnFarrow** [comment]
Planning to do a GUI menu to fix this, I will be making a separate plugin for the GUI menu. 

Why exactly?

I want to make the plugin paid if people want to receive auto-updates via Roblox, it will still be open-source. Plugin will likely cost 5 Robux but to use the old messy plugin, it will still be free because I don't want to make any disruptions to how the plugin works for existing people.

**Comment by TyNoOutlet** [comment]
I know this is pretty old and I'm not sure the last time it was updated but I like this plugin. Only problem is this issue right here. That and the scripts are a bit messy.

I have planned fixes for both of them, so look out for that pull request.
